name: Build Docker Image

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

on: [pull_request]

jobs:
  daqttd-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: daqttd Docker Image
      run: |
          docker build .                                 \
              --file daemon/daqttd/Dockerfile            \
              --build-arg BRNACH_NAME=$BRANCH_NAME       \
              --tag pipeline:$(date +%s)
  example-sinus:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache Conan Dependencies
      id: cache-conan
      uses: actions/cache@v2
      with:
        path: /root/.conan2
        key: ${{ runner.os }}-conan-${{ hashFiles('**/conanfile.txt') }}
    - name: Install conan
      run: pip install conan && conan profile detect
    - name: Create default Conan profile
      if: steps.cache-conan.outputs.cache-hit != 'true'
      run: conan profile detect --force
    - name: Install example dependencies
      run: cd examples/sinus && conan install . -pr:a=default --build=missing -of=/home/runner/.conan2/project/sinus
    - name: Install libdaqtt dependencies
      run: cd daemon/daqttd && conan install conan -pr:a=default --build=missing -of=/home/runner/.conan2/project/daqtt
    - name: Install libdaqtt 
      run: |
        cd daemon/daqttd && \
        cmake -S . \
              -B build \
              -DCMAKE_TOOLCHAIN_FILE=/home/runner/.conan2/project/daqtt/build/Release/generators/conan_toolchain.cmake \
              -DCMAKE_BUILD_TYPE=Release          && \
        cmake --build build                       && \
        sudo cmake --build build --target install
    - name: CMake generate
      run: |
        cd examples/sinus && \
        cmake -S . \
              -B build \
              -DCMAKE_TOOLCHAIN_FILE=/home/runner/.conan2/project/sinus/build/Release/generators/conan_toolchain.cmake \
              -DCMAKE_BUILD_TYPE=Release
    - name: CMake build
      run: cd examples/sinus && cmake --build build
