name: Build Docker Image

on: [push, pull_request]

jobs:
  daqttd-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: daqttd Docker Image
      run: |
          docker build .                                 \
              --file daemon/daqttd/Dockerfile            \
              --build-arg INFLUXDB_INIT_TOKEN=pipeline   \
              --build-arg MOSQUITTO_USERNAME=pipeline    \
              --build-arg MOSQUITTO_PASSWORD=pipeline    \
              --tag pipeline:$(date +%s)
  example-sinus:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache Conan Dependencies
      id: cache-conan
      uses: actions/cache@v2
      with:
        path: /root/.conan2
        key: ${{ runner.os }}-conan-${{ hashFiles('**/conanfile.txt') }}
    - name: Install conan
      run: pip install conan && conan profile detect
    - name: Create default Conan profile
      if: steps.cache-conan.outputs.cache-hit != 'true'
      run: conan profile detect --force
    - name: Install dependencies
      run: cd examples/sinus && conan install . -pr:a=default --build=missing -of=/root/.conan2/project
    - name: CMake generate
      run: |
        cd examples/sinus && \
        cmake -S . \
              -B build \
              -DCMAKE_TOOLCHAIN_FILE=/root/.conan2/project/build/Release/generators/conan_toolchain.cmake \
              -DCMAKE_BUILD_TYPE=Release
    - name: CMake build
      run: cd examples/sinus && cmake --build build
